version: "3.4"

services:
  db:
    image: yadd/lemonldap-ng-pg-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=zz
    healthcheck:
      test: "exit 0"
  base:
    image: yadd/lemonldap-ng-base
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    environment:
      - PG_SERVER=db
      - REDIS_SERVER=qwerty
    depends_on:
      db:
        condition: service_healthy
