name: Build and Publish Docker Images

on:
  push:
    branches: [master]

jobs:
  build-and-push-pg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: yadd/lemonldap-ng-pg-database
      - name: Build and push Docker image for pg
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./pg
          push: true
          tags: yadd/lemonldap-ng-pg-database:latest
          label: ${{ steps.meta.outputs.labels }}
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: yadd/lemonldap-ng-pg-database
          provider: dockerhub
          short_description: 'PostgreSQL database ready to use for LemonLDAP::NG'
          readme_file: 'pg/README.md'

  build-and-push-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: yadd/lemonldap-ng-base
      - name: Build and push Docker image for base
        uses: docker/build-push-action@v2
        with:
          context: ./base
          push: true
          tags: yadd/lemonldap-ng-base:latest
          label: ${{ steps.meta.outputs.labels }}
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: yadd/lemonldap-ng-base
          provider: dockerhub
          short_description: 'Base image for lemonldap-ng dockers'
          readme_file: 'base/README.md'

  build-and-push-portal:
    needs: build-and-push-base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: yadd/lemonldap-ng-portal
      - name: Build and push Docker image for portal
        uses: docker/build-push-action@v2
        with:
          context: ./portal
          push: true
          tags: yadd/lemonldap-ng-portal:latest
          label: ${{ steps.meta.outputs.labels }}
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: yadd/lemonldap-ng-portal
          provider: dockerhub
          short_description: 'LemonLDAP::NG Portal'
          readme_file: 'portal/README.md'

  build-and-push-manager:
    needs: build-and-push-base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: yadd/lemonldap-ng-manager
      - name: Build and push Docker image for manager
        uses: docker/build-push-action@v2
        with:
          context: ./manager
          push: true
          tags: yadd/lemonldap-ng-manager:latest
          label: ${{ steps.meta.outputs.labels }}
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: yadd/lemonldap-ng-manager
          provider: dockerhub
          short_description: 'LemonLDAP::NG Manager'
          readme_file: 'manager/README.md'

  build-and-push-full:
    needs: build-and-push-portal
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: yadd/lemonldap-ng-full
      - name: Build and push Docker image for full
        uses: docker/build-push-action@v2
        with:
          context: ./full
          push: true
          tags: yadd/lemonldap-ng-full:latest
          label: ${{ steps.meta.outputs.labels }}
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: yadd/lemonldap-ng-full
          provider: dockerhub
          short_description: 'LemonLDAP::NG Portal and Manager'
          readme_file: 'full/README.md'

  build-and-push-dev:
    needs: build-and-push-full
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Test with environment variables
        run: echo $TAG_NAME
        env:
          TAG_NAME: 2.0.16-${{ steps.date.outputs.date }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: yadd/lemonldap-ng-dev
      - name: Build and push Docker image for dev
        uses: docker/build-push-action@v2
        with:
          context: ./dev
          push: true
          tags: yadd/lemonldap-ng-dev:2.0.16-${{ steps.date.outputs.date }}
          label: ${{ steps.meta.outputs.labels }}
