name: Build and Publish Docker Images

on:
  push:
    branches: [master]

jobs:
  build-and-push-pg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: yadd/lemonldap-ng-pg-database
      - name: Build and push Docker image for pg
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./pg
          push: true
          tags: yadd/lemonldap-ng-pg-database:latest
          label: ${{ steps.meta.outputs.labels }}
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: yadd/lemonldap-ng-pg-database
          provider: dockerhub
          short_description: 'Base image for lemonldap-ng dockers'
          readme_file: 'pg/README.md'

  build-and-push-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: yadd/lemonldap-ng-base
      - name: Build and push Docker image for base
        uses: docker/build-push-action@v2
        with:
          context: ./base
          push: true
          tags: yadd/lemonldap-ng-base:latest
          label: ${{ steps.meta.outputs.labels }}
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: yadd/lemonldap-ng-base
          provider: dockerhub
          short_description: 'Base image for lemonldap-ng dockers'
          readme_file: 'base/README.md'

  build-and-push-portal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: yadd/lemonldap-ng-portal
      - name: Build and push Docker image for portal
        uses: docker/build-push-action@v2
        with:
          context: ./portal
          push: true
          tags: yadd/lemonldap-ng-portal:latest
          label: ${{ steps.meta.outputs.labels }}
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: yadd/lemonldap-ng-portal
          provider: dockerhub
          short_description: 'Base image for lemonldap-ng dockers'
          readme_file: 'portal/README.md'
