name: Build and Publish Docker Images

on:
  push:
    branches: [master]

jobs:
  build-and-push-pg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image for app1
        uses: docker/build-push-action@v2
        with:
          context: ./pg
          push: true
          tags: yadd/lemonldap-ng-pg-database:latest

  build-and-push-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image for app2
        uses: docker/build-push-action@v2
        with:
          context: ./base
          push: true
          tags: yadd/lemonldap-ng-base:latest
